### ISSUE TITLE
[BUG] The GitOps reconciliation is out of sync while the service was fixed

### ISSUE THREAD

**Issue by JayChanggithub** [SAP/crossplane-provider-btp#104]
Hi Colleagues,
We encountered a strange issue. We updated the API to the latest version and observed that the Kyma status was previously fine. However, in the past couple of days, the BTP cockpit suddenly started showing a failure status, with a 503 error appearing unexpectedly.
I have raised a internal JIRA with the Kyma team for clarification. Their feedback suggests that updating via the UI cockpit works fine, but using the IAD + GitOps method results in an error, as detailed in the ticket.
Could someone help us with this issue?. The GitOps repositories. 

**Tested with Provider Version**

```yaml
    externalSecretsOperator:
      version: 0.11.0
    flux:
      version: 2.14.0
    crossplane:
      version: 1.18.0
      providers:
        - name: btp
          version: 1.0.2
        - name: kubernetes
          version: 0.15.0
        - name: ias
          version: 0.2.0
        - name: vault
          version: 1.0.0
        - name: argocd
          version: 0.9.1
```

**To Reproduce**
1.  Go to cockpit found KYMA status fail, since the 503 service error.  `k get kymaenvironments.environment.btp.sap.crossplane.io -oyaml `
    ```bash
    stateMessage: 'Unexpected error during service instance request processing with
        ID [B7F80B22-B788-4822-A220-3C734CB89D57], Reason: 503 Service Unavailable'
      subaccountGUID: c89e8123-119e-413b-99da-e47a68decc08
      tenantId: c89e8123-119e-413b-99da-e47a68decc08
      type: Update
    ```
2. Updated cockpit UI and then the status back to fine.
3. Updated the GitOps repository then will trigger reconciled again.

**Expected behavior**
When the underlying API issue (such as the 503 error) is resolved, GitOps should automatically reconcile and reflect the latest status, rather than requiring a manual update through the cockpit to trigger the changes.

**Screenshots**

<img width="736" alt="Image" src="https://github.com/user-attachments/assets/1c492cef-2610-4a50-bc2b-ee5d0bae3171" />

**Additional context**

```bash
$ k get gitrepositories.source.toolkit.fluxcd.io     
NAME                 URL                                                         AGE   READY   STATUS
k-sre-slow-us21-co   https://github.tools.sap/rgm/infra-cloud-orchestrator-rgm   16d   True    stored artifact for revision 'main@sha1:0d3bfb999fdbf537f5d406ae9d069e1e42826180'

$ k get helmreleases.helm.toolkit.fluxcd.io 
NAME          AGE   READY   STATUS
helmrelease   16d   True    Helm upgrade succeeded for release default/default-helmrelease.v12 with chart k-sre-slow-us21-co@1.0.0+0d3bfb999fdb


$ k get kymaenvironments.environment.btp.sap.crossplane.io   
NAME                 READY   SYNCED   EXTERNAL-NAME        AGE
k-sre-slow-us21-co   False   True     k-sre-slow-us21-co   16d

$ k get kymaenvironments.environment.btp.sap.crossplane.io -oyaml 
apiVersion: v1
items:
- apiVersion: environment.btp.sap.crossplane.io/v1alpha1
  kind: KymaEnvironment
  metadata:
    annotations:
      crossplane.io/external-create-pending: "2025-01-24T15:00:30Z"
      crossplane.io/external-create-succeeded: "2025-01-24T15:00:35Z"
      crossplane.io/external-name: k-sre-slow-us21-co
      meta.helm.sh/release-name: default-helmrelease
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2025-01-24T14:56:46Z"
    finalizers:
    - finalizer.managedresource.crossplane.io
    generation: 5
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: helmrelease
      helm.toolkit.fluxcd.io/namespace: default
    name: k-sre-slow-us21-co
    resourceVersion: "25740432"
    uid: 09b4d1f9-96ec-483d-8bba-548b074e6c1b
  spec:
    cloudManagementRef:
      name: k-sre-slow-us21-co
    cloudManagementSecret: k-sre-slow-us21-co-cis-local
    cloudManagementSecretNamespace: default
    cloudManagementSubaccountGuid: c89e8123-119e-413b-99da-e47a68decc08
    deletionPolicy: Delete
    forProvider:
      parameters:
        administrators:
        - k-sre-slow-us21-co@sap.com
        - chieh-chuan.chang@sap.com
        - james.zhang08@sap.com
        - niko.chen@sap.com
        autoScalerMax: 8
        autoScalerMin: 5
        machineType: Standard_D8s_v5
        oidc:
          clientID: f93df437-1bd3-40cd-8458-0a48bd8cb51c
          groupsClaim: groups
          issuerURL: https://devexpdev.accounts.ondemand.com
          signingAlgs:
          - RS256
          usernameClaim: email
          usernamePrefix: '-'
        region: eastus
      planName: azure
    managementPolicies:
    - '*'
    providerConfigRef:
      name: account-provider-config
    subaccountGuid: c89e8123-119e-413b-99da-e47a68decc08
    subaccountRef:
      name: k-sre-slow-us21-co
    writeConnectionSecretToRef:
      name: k-sre-slow-us21-co-kyma-environment
      namespace: default
  status:
    atProvider:
      brokerId: 1B1719DE-CC81-4686-A9E2-4631AA82D2BD
      createdDate: "1737730818048.000000"
      customLabels: {}
      dashboardUrl: https://dashboard.kyma.cloud.sap/?kubeconfigID=B7F80B22-B788-4822-A220-3C734CB89D57
      description: created via crossplane-provider-btp-account
      environmentType: kyma
      globalAccountGUID: 2291c59f-008e-432d-a082-e3b49f9b5e26
      id: B7F80B22-B788-4822-A220-3C734CB89D57
      labels: '{"APIServerURL":"https://api.c-81b1e06.kyma.ondemand.com","KubeconfigURL":"https://kyma-env-broker.cp.kyma.cloud.sap/kubeconfig/B7F80B22-B788-4822-A220-3C734CB89D57","Name":"k-sre-slow-us21-co"}'
      modifiedDate: "1738759864320.000000"
      name: k-sre-slow-us21-co
      operation: b2fe6e56-0d92-4d38-ae1d-549367c8d8de
      parameters: '{"autoScalerMin":5,"autoScalerMax":10,"name":"k-sre-slow-us21-co","machineType":"Standard_D8s_v5","region":"eastus","administrators":["k-sre-slow-us21-co@sap.com","chieh-chuan.chang@sap.com","james.zhang08@sap.com","niko.chen@sap.com"],"oidc":{"clientID":"f93df437-1bd3-40cd-8458-0a48bd8cb51c","groupsClaim":"groups","issuerURL":"https://devexpdev.accounts.ondemand.com","signingAlgs":["RS256"],"usernameClaim":"email","usernamePrefix":"-"}}'
      planId: 4deee563-e5ec-4731-b9b1-53b42d855f0c
      planName: azure
      platformId: 612ad16e-d6e5-41fc-9ea5-c05a00ff90dd
      serviceId: 47c9dcbf-ff30-448e-ab36-d3bad66ba281
      serviceName: kymaruntime
      state: UPDATE_FAILED
      stateMessage: 'Unexpected error during service instance request processing with
        ID [B7F80B22-B788-4822-A220-3C734CB89D57], Reason: 503 Service Unavailable'
      subaccountGUID: c89e8123-119e-413b-99da-e47a68decc08
      tenantId: c89e8123-119e-413b-99da-e47a68decc08
      type: Update
    conditions:
    - lastTransitionTime: "2025-01-24T15:00:35Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2025-02-05T12:50:49Z"
      reason: Unavailable
      status: "False"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
```

**Comment by sdischer-sap** [comment]
@JayChanggithub same question here I guess ;) 
Is the issue resolved? WIth the fix of the provider to avoid continous kyma updates I would hope this side affect should be fixed as well?

**Comment by JayChanggithub** [comment]
@sdischer-sap 
Yes, when I upgrade the BTP provider to the latest version (1.0.3), the issue should be fixed. However, errors still occasionally occur. But not very always.
